= `coq2html` alternative css =

This css file is an alternative style for the documentation generated by https://github.com/xavierleroy/coq2html[coq2html].

== Use ==

You can use it in two ways:

- If you want to use it for a single project, put it in the folder where the documentation is generated (without renaming it)
- If you want it to be the default style whenever `coq2html` is called, clone the repository of `coq2html`, replace the CSS stylesheet in the cloned folder by the custom stylesheet of this repository, rebuild and reinstall `coq2html`.

== Optional dependencies ==

This CSS stylesheet tries to find the following (nicer) fonts on the computer the documentation is read on:

- https://fonts.google.com/specimen/Open+Sans[Open Sans] for regular text
- https://www.jetbrains.com/lp/mono/[JetBrains Mono] for proof scripts

When one of these fonts is not found, the font used by the original `coq2html` style is used.

If you want to host the fonts on a server or rely on a third-party service to provide them, you should change the `@font-face` blocks in the stylesheet. Here is https://developer.mozilla.org/fr/docs/Web/CSS/@font-face[documentation] for this CSS rule.
